name:  Continues Integration - Static Web

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '21 4 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript'  ]
        node-version: [20.x]


    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build static site judotech.web
      run: |
        cd ./source/judotech.web
        npm install
        gulp --production
        
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        dotnet-version: ${{ matrix.dotnet-version }}
   
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
        
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob delete-batch --account-name storagejudotech --auth-mode key -s '$web'
          az storage blob upload-batch --account-name storagejudotech --auth-mode key -s ./source/judotech.web/public -d '$web' 
    #- name: Purge CDN endpoint
    #  uses: azure/CLI@v1
    #  with:
    #    inlineScript: |
    #       az cdn endpoint purge --content-paths  "/*" --profile-name "CDN_PROFILE_NAME" --name "CDN_ENDPOINT" --resource-group "RESOURCE_GROUP"
    
    - name: logout
      run: |
            az logout
      if: always()
        
